import {createPortraitMotion} from './portrait-motion.js';
export function createCeoView({getSnapshot}) {
 const office=document.getElementById('office-view');
 const view=document.createElement('section');view.id='ceo-view';view.hidden=true;view.setAttribute('aria-label','TOMAとの一対一の相談');
 view.innerHTML=`<div class="ceo-heading"><button id="ceo-back">← オフィスに戻る</button><span>OWNER & TOMA · ふたりの相談室</span></div><div class="ceo-layout"><div class="ceo-room" data-mode="listening"><div class="ceo-window"></div><div class="ceo-books"><i></i><i></i><i></i><i></i></div><div class="ceo-room-label">TOMATOAI COMPANY<small>小さな相談から、はじめよう。</small></div><div class="ceo-seat"><div class="ceo-portrait" role="img" aria-label="話を聞いているTOMA"><div class="ceo-portrait-art"></div><div class="ceo-emotion-art"></div></div></div><div class="ceo-desk"><div class="ceo-desk-props"><img src="assets/ceo-desk-props.png" alt="トマトロゴの薄いアルミ製パソコンと、陶器のコーヒーカップ、机に置いたノート" width="2172" height="724"/><i aria-hidden="true"></i></div><div class="ceo-laptop" role="img" aria-label="トマトロゴのアルミ製ノートパソコン"><svg class="ceo-tomato-logo" viewBox="0 0 64 64" aria-hidden="true"><path d="M31 22C21 16 9 24 9 37c0 13 10 21 23 21s23-8 23-21c0-13-12-21-23-15Z"/><path d="M31 24 18 19l9-3-6-9 12 7 9-8-2 10 12 3-14 6-4-7Z"/><path d="M31 19c-2-7 0-12 4-16l3 2c-4 4-5 8-4 14Z"/></svg></div><div class="ceo-cup"><img src="assets/ceo-mug.png" alt="トマトマークの陶器のコーヒーカップ"/><i></i></div><div class="ceo-notebook"></div></div><div class="ceo-presence"><i></i><span id="ceo-status">うん、聞いてるよ。</span></div></div><div class="ceo-conversation"><span class="ceo-eyebrow">YOUR PARTNER</span><h2>TOMA <small>CEO・あなたの相談役</small></h2><p class="ceo-welcome">まとまってなくても、大丈夫。<br>いま考えていること、聞かせて？</p><details class="ceo-emotions"><summary>表情を見てみる ♡</summary><div><button type="button" data-emotion="happy">にっこり</button><button type="button" data-emotion="excited">ワクワク</button><button type="button" data-emotion="focused">真剣</button><button type="button" data-emotion="worried">困り顔</button><button type="button" data-emotion="shy">てれてれ</button><button type="button" data-emotion="sleepy">うとうと</button><button type="button" data-emotion="relieved">ほっとする</button><button type="button" data-emotion="surprised">びっくり</button><button type="button" data-emotion="curious">きょとん</button><button type="button" data-emotion="amused">くすくす</button><button type="button" data-emotion="wink">ウインク</button><button type="button" data-emotion="determined">まかせて</button></div></details><div id="ceo-messages" role="log" aria-label="TOMAとの会話" aria-live="polite"></div><div class="ceo-suggestions"><button type="button">今日の仕事は？</button><button type="button">アイデアを相談したい</button><button type="button">ちょっと疲れた</button></div><form id="ceo-form"><label for="ceo-input">TOMAに話しかける</label><div><textarea id="ceo-input" rows="2" maxlength="600" placeholder="ねえTOMA、こんなこと考えてるんだけど…" required></textarea><button type="submit" aria-label="TOMAに送信">↑</button></div></form><p class="ceo-demo-note">会話デモ · 入力に合わせた定型の案内です。AI回答は未接続。</p></div></div>`;
 office.after(view);
 const room=view.querySelector('.ceo-room'),input=view.querySelector('#ceo-input'),form=view.querySelector('form'),log=view.querySelector('#ceo-messages'),send=form.querySelector('button');
 const opener=document.createElement('button');opener.id='ceo-open';opener.textContent='TOMAに相談する ♡';document.querySelector('.scene-caption').append(opener);
 let returnFocus=opener,busy=false,timer=null,blinkTimer=null,idleTimer=null,gestureTimer=null;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const portrait=view.querySelector('.ceo-portrait'),motion=createPortraitMotion(portrait,{reduced});motion.show('listening');
 function gesture(name){if(reduced.matches)return;clearTimeout(gestureTimer);delete room.dataset.gesture;requestAnimationFrame(()=>{room.dataset.gesture=name;gestureTimer=setTimeout(()=>delete room.dataset.gesture,1800);});}
 function pose(mode){delete room.dataset.emotion;room.classList.remove('is-blinking');room.dataset.mode=mode;motion.show(mode);if(mode==='thinking')gesture('tilt');else if(mode==='replying')gesture('nod');view.querySelector('.ceo-portrait').setAttribute('aria-label',({listening:'話を聞いている',thinking:'考えている',replying:'笑顔で返事をしている'})[mode]+'TOMA');view.querySelector('#ceo-status').textContent=({listening:'うん、聞いてるよ。',thinking:'ふむふむ…ちょっと考えるね。',replying:'いっしょに考えていこう♪'})[mode];}
 const emotionLabels={happy:'にっこり♪',excited:'わぁ、楽しみ！',focused:'ちゃんと聞いてるよ。',worried:'うん…いっしょに考えよう。',shy:'えへへ、ありがとう♡',sleepy:'ふぁ…ちょっと眠いね。',relieved:'よかった…ほっとしたね♪',surprised:'わぁ、そうなの？',curious:'ん？もう少し聞かせて？',amused:'ふふ、楽しいね♪',wink:'ふふっ、まかせて♡',determined:'よし、いっしょにやろう！'};
 function emotion(name){if(!Object.hasOwn(emotionLabels,name))return;room.classList.remove('is-blinking');room.dataset.emotion=name;motion.show(room.dataset.mode,name);gesture(['curious','worried','shy'].includes(name)?'tilt':'nod');view.querySelector('#ceo-status').textContent=emotionLabels[name];view.querySelector('.ceo-portrait').setAttribute('aria-label',emotionLabels[name]+'という表情のTOMA');}
 function reaction(text){if(/びっくり|驚|すごい/.test(text))return 'surprised';if(/安心|よかった|解決/.test(text))return 'relieved';if(/面白|おもしろ|笑/.test(text))return 'amused';if(/お願い|頼む|まかせ/.test(text))return 'determined';if(/どういう|わから|分から/.test(text))return 'curious';if(/仕事|進捗|みんな/.test(text))return 'focused';if(/眠|寝/.test(text))return 'sleepy';if(/疲|つら|困|不安|心配/.test(text))return 'worried';if(/ありがとう|かわいい|可愛い|好き/.test(text))return 'shy';if(/アイデア|作り|企画/.test(text))return 'excited';return 'happy';}
 view.querySelectorAll('.ceo-emotions button').forEach(b=>b.onclick=()=>{if(busy)return;if(timer){clearTimeout(timer);timer=null;}pose('listening');emotion(b.dataset.emotion);});
 function message(role,text){const p=document.createElement('p');p.className='ceo-message '+role;p.textContent=text;log.append(p);log.scrollTop=log.scrollHeight;}
 message('toma','来てくれてうれしい♪ 今日は何から話そうか？');
 function reply(text){
  if(/仕事|進捗|みんな/.test(text)){const s=getSnapshot(),names={research:'LYCO（リコ）・リサーチ',analyst:'SOL（ソル）・分析・戦略',creator:'POMO（ポモ）・制作',critic:'RUBY（ルビー）・品質管理',ceo:'TOMA・CEO'},states={idle:'待機中',walking:'移動中',researching:'資料を読んでいるよ',analyzing:'分析中',creating:'制作中',reviewing:'確認中',handoff:'資料をお届け中',resting:'ひと休み中',dozing:'うとうと中',sleeping:'おやすみ中',completed:'作業完了',rejected:'修正を相談中'};return 'いまのオフィスの様子だよ♪\n'+Object.entries(s.agents).map(([id,a])=>`${names[id]}：${states[a.status]||a.status}`).join('\n')+`\n納品BOXには${s.deliveries.length}件あるよ。`;}
  if(/疲|休|つら|眠/.test(text))return 'そっか、おつかれさま。いったんひと息つこう♪\n急いで決めなくて大丈夫。休んだあとで、いちばん小さな一歩をいっしょに考えよう。';
  if(/アイデア|作り|企画|相談/.test(text))return 'いいね、聞かせて♪\nまず「誰に届けたいか」と「どんな気持ちになってほしいか」をひとつずつ教えて？ そこから形を考えていこう。';
  return '話してくれてありがとう♪\nその話で、いちばん大事にしたいことは何かな？ まずそこから、ひとつずつ整理してみよう。';
 }
 function submit(text){if(busy||!text.trim())return;busy=true;message('owner',text.trim());input.value='';send.disabled=true;view.querySelectorAll('.ceo-suggestions button').forEach(b=>b.disabled=true);view.querySelectorAll('.ceo-emotions button').forEach(b=>b.disabled=true);pose('thinking');timer=setTimeout(()=>{message('toma',reply(text));pose('replying');emotion(reaction(text));view.querySelectorAll('.ceo-emotions button').forEach(b=>b.disabled=false);busy=false;send.disabled=false;view.querySelectorAll('.ceo-suggestions button').forEach(b=>b.disabled=false);timer=setTimeout(()=>{pose('listening');timer=null;},4200);},1600);}
 form.onsubmit=e=>{e.preventDefault();if(timer&&!busy){clearTimeout(timer);timer=null;}submit(input.value);};
 input.addEventListener('input',()=>{if(!busy)pose('listening');});
 view.querySelectorAll('.ceo-suggestions button').forEach(b=>b.onclick=()=>{if(timer&&!busy)clearTimeout(timer);submit(b.textContent);});
 function open(source=opener){returnFocus=source;office.hidden=true;view.hidden=false;document.body.classList.add('ceo-active');view.querySelector('#ceo-back').focus();if(!reduced.matches&&!blinkTimer)blinkTimer=setInterval(()=>{if(view.hidden||room.dataset.mode!=='listening'||room.dataset.emotion)return;room.classList.add('is-blinking');motion.show('listening',null,true);setTimeout(()=>{room.classList.remove('is-blinking');motion.show(room.dataset.mode,room.dataset.emotion);},240);},6100);if(!reduced.matches&&!idleTimer)idleTimer=setInterval(()=>{if(!view.hidden&&!busy&&room.dataset.mode==='listening')gesture(room.dataset.emotion==='curious'?'tilt':'nod');},9300);}
 function close(){view.hidden=true;office.hidden=false;document.body.classList.remove('ceo-active');clearInterval(blinkTimer);blinkTimer=null;clearInterval(idleTimer);idleTimer=null;clearTimeout(gestureTimer);delete room.dataset.gesture;room.classList.remove('is-blinking');returnFocus.focus();}
 opener.onclick=()=>open();view.querySelector('#ceo-back').onclick=close;
 return {open,close,isOpen:()=>!view.hidden};
}
